<p>nginx_1.9</p>
<p>https://code.aliyun.com/jy1779/nginx_1.9.git</p>
<p>myproject</p>
<p>https://code.aliyun.com/jy1779/myproject.git</p>
<p>zabbix3.2</p>
<p>https://code.aliyun.com/jy1779/zabbix3.2.git</p>
<p>php7.0</p>
<p>https://code.aliyun.com/jy1779/php7.0.git</p>
<p>varnish4.0</p>
<p>https://code.aliyun.com/jy1779/varnish4.0.git</p>
<p>docker_install</p>
<p>https://code.aliyun.com/jy1779/docker_install.git</p>
<p>jenkins</p>
<p>https://code.aliyun.com/jy1779/jenkins.git</p>
<p>mysql_5.6</p>
<p>https://code.aliyun.com/jy1779/mysql_5.6.git</p>
<p>ExtendedMysqlSlave</p>
<p>https://code.aliyun.com/jy1779/ExtendedMysqlSlave.git</p>
<p>mysql-5.6-xtrabackup</p>
<p>https://code.aliyun.com/jy1779/mysql-5.6-xtrabackup.git</p>
<p>command</p>
<p>https://code.aliyun.com/jy1779/command.git</p>
<p>be</p>
<p>https://code.aliyun.com/jy1779/be.git</p>
<p>redis3.2</p>
<p>https://code.aliyun.com/jy1779/redis3.2.git</p>
<p>tomcat8</p>
<p>https://code.aliyun.com/jy1779/tomcat8.git</p>
<p>python3.5</p>
<p>https://code.aliyun.com/jy1779/python3.5.git</p>
<p>elk</p>
<p>https://code.aliyun.com/jy1779/elk.git</p>
